In [1]:
import pandas as pd
import os

In [2]:
list_files = os.listdir("../")
list_files

['.git',
 'away_team.csv',
 'away_team_score.csv',
 'event.csv',
 'home_team.csv',
 'home_team_score.csv',
 'Javadi',
 'notebook.ipynb',
 'odds.csv',
 'pbp.csv',
 'power.csv',
 'round.csv',
 'season.csv',
 'statistics.csv',
 'time.csv',
 'tournament.csv',
 'venue.csv',
 'votes.csv']

In [16]:
df = pd.read_csv("../away_team_score.csv")
df

,match_id,current_score,display_score,period_1,period_2,period_3,period_4,period_5,period_1_tie_break,period_2_tie_break,period_3_tie_break,period_4_tie_break,period_5_tie_break,normal_time
0,11974053,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11974066,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11998445,2.0,2.0,7.0,2.0,7.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN
3,11998446,2.0,2.0,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11998447,0.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35048,12213482,0.0,0.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35049,12213483,0.0,0.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35050,12213484,0.0,0.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35051,12213486,0.0,0.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35052,12213803,0.0,0.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Question 1

In [70]:
df_home = pd.read_csv("../home_team.csv")
df_away = pd.read_csv("../away_team.csv")

In [69]:
all_players = pd.concat([
    df_home[['player_id', 'full_name' , 'height']],
    df_away[['player_id', 'full_name' , 'height']]
], ignore_index=True)
all_players

       player_id               full_name  height
0         287803          Cazaux, Arthur    1.83
1          62790     Lestienne, Constant    1.80
2          64580            Ćorić, Borna    1.88
3         131442           Mmoh, Michael    1.88
4          22218           Paire, Benoit    1.96
...          ...                     ...     ...
49808      72324          Doria, Luciano    1.80
49809     217437  Soriano Barrera, Adria    1.91
49810     108559        Taberner, Carlos    1.83
49811      74679         Simonsson, Fred    1.88
49812     220540           Lumsden, Ewen     NaN

[49813 rows x 3 columns]

In [46]:
all_players = all_players.dropna(subset=['player_id'])
unique_players = all_players.drop_duplicates(subset='player_id')
unique_players.sort_values(["player_id"])

       player_id           full_name  height
5680       14414    Gasquet, Richard    1.83
39866      14486       Nadal, Rafael    1.85
4168       14548      Wawrinka, Stan    1.83
7636       14844       Monfils, Gaël    1.93
15641      14882     Djokovic, Novak    1.88
...          ...                 ...     ...
38232     489714  McNeil, Christasha     NaN
11771     490732         Bidan, Fadi     NaN
44156     498399        Jialin, Tian     NaN
23552     499834      Moeller, Elmer    1.83
49411     509586    Almeida, Joaquim     NaN

[2644 rows x 3 columns]

In [47]:
print(f"Total number of players: {unique_players["player_id"].count()}")

Total number of players: 2644

# Question 2

In [48]:
average_height = unique_players["height"].mean().round(2)
print(f"The average height of players is: {average_height}")

The average height of players is: 1.82

In [49]:
player_counts = unique_players["player_id"].count()
with_height = unique_players.dropna(subset=["height"])
without_height = player_counts - (with_height['player_id'].count())

print(f"For {without_height} number of players ({(without_height / player_counts):.2f} %), we don't have their hieght's data")

For 1327 number of players (0.50 %), we don't have their hieght's data

# Question 3

In [10]:
df = pd.read_csv("../event.csv")
df.dropna(subset=["winner_code"])

,match_id,first_to_serve,home_team_seed,away_team_seed,custom_id,winner_code,default_period_count,start_datetime,match_slug,final_result_only
0,11974053,NaN,NaN,NaN,NNfsQTf,1.0,3,1706878800,switzerland-netherlands,False
1,11974066,NaN,NaN,NaN,hTfsrpg,2.0,3,1706871600,ukraine-usa,False
2,11998445,1.0,NaN,3,nPBbsdgpc,2.0,3,1706810400,cazaux-auger-aliassime,False
3,11998446,2.0,NaN,NaN,PfAsFyjc,2.0,3,1706800800,cobolli-lestienne,False
4,11998447,1.0,4,NaN,FQAsyUF,1.0,3,1706794200,martinez-coric,False
...,...,...,...,...,...,...,...,...,...,...
35048,12213482,2.0,NaN,NaN,TpwcsODcd,1.0,3,1711978500,benito-fernandez-baldovinetti,False
35049,12213483,1.0,NaN,NaN,QxJcsjbVc,1.0,3,1711978200,schinteie-kypriotis,False
35050,12213484,2.0,NaN,NaN,yLPbsvyXb,1.0,3,1711978200,hornitschek-hornung,False
35051,12213486,2.0,NaN,NaN,qzqbstjac,1.0,3,1711978200,agostinetto-cano,False
35052,12213803,NaN,NaN,NaN,nvqcsGbJc,1.0,3,1711978200,ferri-trunov,False

In [71]:
df_event = pd.read_csv("../event.csv")

In [72]:
player_id = 14882 #Novak Djokovic 

home_matches = df_home[df_home['player_id'] == player_id]['match_id']
away_matches = df_away[df_away['player_id'] == player_id]['match_id']

all_match_ids = pd.concat([home_matches, away_matches]).unique()

player_matches = df_event[df_event['match_id'].isin(all_match_ids)]

player_matches = player_matches.merge(df_home[['match_id', 'player_id', 'full_name']], on='match_id', how='left') \
                               .rename(columns={'player_id': 'home_player_id', 'full_name': 'home_full_name'})

player_matches = player_matches.merge(df_away[['match_id', 'player_id', 'full_name']], on='match_id', how='left') \
                               .rename(columns={'player_id': 'away_player_id', 'full_name': 'away_full_name'})

In [19]:
player_matches

,match_id,first_to_serve,home_team_seed,away_team_seed,custom_id,winner_code,default_period_count,start_datetime,match_slug,final_result_only,home_player_id,home_full_name,away_player_id,away_full_name
0,12109982,2.0,NaN,NaN,HXfsgTZ,1.0,3,1710025800,vukic-djokovic,False,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
1,12109982,2.0,NaN,NaN,HXfsgTZ,1.0,3,1710025800,vukic-djokovic,False,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
2,12109982,2.0,NaN,NaN,HXfsgTZ,1.0,3,1710025800,vukic-djokovic,False,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
3,12109982,2.0,NaN,NaN,HXfsgTZ,1.0,3,1710025800,vukic-djokovic,False,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
4,12109982,2.0,NaN,NaN,HXfrgTZ,1.0,3,1710029400,vukic-djokovic,True,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
5,12109982,2.0,NaN,NaN,HXfrgTZ,1.0,3,1710029400,vukic-djokovic,True,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
6,12109982,2.0,NaN,NaN,HXfrgTZ,1.0,3,1710029400,vukic-djokovic,True,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
7,12109982,2.0,NaN,NaN,HXfrgTZ,1.0,3,1710029400,vukic-djokovic,True,14882,"Djokovic, Novak",124656,"Vukić, Aleksandar"
8,12109939,1.0,NaN,NaN,HXfsIJpo,2.0,3,1710203400,nardi-djokovic,True,14882,"Djokovic, Novak",289233,"Nardi, Luca"
9,12109939,1.0,NaN,NaN,HXfsIJpo,2.0,3,1710203400,nardi-djokovic,True,14882,"Djokovic, Novak",289233,"Nardi, Luca"
10,12109939,1.0,NaN,NaN,HXfsIJpo,2.0,3,1710203400,nardi-djokovic,True,14882,"Djokovic, Novak",289233,"Nardi, Luca"
11,12109939,1.0,NaN,NaN,HXfsIJpo,2.0,3,1710203400,nardi-djokovic,True,14882,"Djokovic, Novak",289233,"Nardi, Luca"
12,12109939,1.0,NaN,NaN,HXfsIJpc,2.0,3,1710205200,nardi-djokovic,False,14882,"Djokovic, Novak",289233,"Nardi, Luca"
13,12109939,1.0,NaN,NaN,HXfsIJpc,2.0,3,1710205200,nardi-djokovic,False,14882,"Djokovic, Novak",289233,"Nardi, Luca"
14,12109939,1.0,NaN,NaN,HXfsIJpc,2.0,3,1710205200,nardi-djokovic,False,14882,"Djokovic, Novak",289233,"Nardi, Luca"
15,12109939,1.0,NaN,NaN,HXfsIJpc,2.0,3,1710205200,nardi-djokovic,False,14882,"Djokovic, Novak",289233,"Nardi, Luca"

In [73]:
df_event_clean = df_event[['match_id', 'winner_code' , 'start_datetime']].drop_duplicates(subset=['match_id'])
df_home_clean = df_home[['match_id', 'player_id', 'full_name']].drop_duplicates(subset=['match_id'])
df_away_clean = df_away[['match_id', 'player_id', 'full_name']].drop_duplicates(subset=['match_id'])

In [74]:
df_winner = (df_event_clean[['match_id', 'winner_code']]
    .merge(df_home_clean[['match_id', 'player_id', 'full_name']], on='match_id', how='left')
    .rename(columns={'player_id': 'home_player_id', 'full_name': 'home_full_name'})
    .merge(df_away_clean[['match_id', 'player_id', 'full_name']], on='match_id', how='left')
    .rename(columns={'player_id': 'away_player_id', 'full_name': 'away_full_name'}))
df_winner

,match_id,winner_code,home_player_id,home_full_name,away_player_id,away_full_name
0,11974053,1.0,NaN,NaN,NaN,NaN
1,11974066,2.0,NaN,NaN,NaN,NaN
2,11998445,2.0,287803.0,"Cazaux, Arthur",192013.0,"Auger-Aliassime, Felix"
3,11998446,2.0,62790.0,"Lestienne, Constant",273680.0,Flavio Cobolli
4,11998447,1.0,64580.0,"Ćorić, Borna",77223.0,"Martinez, Pedro"
...,...,...,...,...,...,...
16868,12213482,1.0,303293.0,"Baldovinetti, Guelfo",NaN,NaN
16869,12213483,1.0,NaN,NaN,NaN,NaN
16870,12213484,1.0,243670.0,"Hornitschek, Nico",NaN,NaN
16871,12213486,1.0,NaN,NaN,NaN,NaN
16872,12213803,1.0,NaN,NaN,NaN,NaN

In [ ]:
home_wins = (df_winner[df_winner['winner_code'] == 1]
             .dropna(subset=['home_player_id', 'home_full_name'])
             .groupby(['home_player_id', 'home_full_name']).size().reset_index(name='wins'))
home_wins = home_wins.rename(columns={'home_player_id': 'player_id', 'home_full_name': 'full_name'})

away_wins = (df_winner[df_winner['winner_code'] == 2]
             .dropna(subset=['away_player_id', 'away_full_name'])
             .groupby(['away_player_id', 'away_full_name']).size().reset_index(name='wins'))
away_wins = away_wins.rename(columns={'away_player_id': 'player_id', 'away_full_name': 'full_name'})

away_wins

      player_id                 full_name  wins
0       14414.0          Gasquet, Richard     7
1       14844.0             Monfils, Gaël     4
2       15126.0              Murray, Andy     1
3       15434.0            Fognini, Fabio     1
4       15858.0             Elias, Gastão     6
...         ...                       ...   ...
1877   482562.0              Wang, Qiulin     4
1878   483188.0     Budkov Kjaer, Nicolai     3
1879   486072.0                Kim, Yujin     3
1880   488404.0  Wendler Filho, Jefferson     1
1881   490732.0               Bidan, Fadi     1

[1882 rows x 3 columns]

In [76]:
total_wins = (pd.concat([home_wins, away_wins])
               .groupby(['player_id', 'full_name'])['wins']
               .sum()
               .reset_index()
               .sort_values('wins', ascending=False))

print(total_wins.head(1))

     player_id      full_name  wins
184    50901.0  Popko, Dmitry    29